name: ${APP_NAME}
services:
  database:
    container_name: ${APP_NAME}-database
    restart: always
    image: postgres:18.4-alpine
    ports:
      - 5432:5432
    networks:
      - isolated
    volumes:
      - psql-data:/var/lib/postgresql
      - ./migration.sql://docker-entrypoint-initdb.d/migration.sql:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  database-manager:
    container_name: database-manager
    image: dpage/pgadmin4:9.15.0
    ports:
      - 4444:80
    networks:
      - isolated
    volumes:
      - db-manager_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database

  server:
    container_name: ${APP_NAME}-server
    restart: always
    image: ${APP_NAME}/spring:1.0
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
      target: spring
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - isolated
    depends_on:
      - database

  web:
    container_name: ${APP_NAME}-web
    restart: always
    image: ${APP_NAME}/angular:1.4
    build:
      context: ./
      dockerfile: Dockerfile
      target: angular
    networks:
      - isolated
    depends_on:
      - database

networks:
  isolated:
    internal: true
    driver: bridge
  shared:
    driver: bridge

volumes:
  psql-data:
  db-manager_data:
