name: ${APP_NAME}
services:
  database:
    container_name: ${APP_NAME}-database
    restart: always
    image: postgres:18.4-alpine
    ports:
      - host_ip: 127.0.0.1
        published: 5432
        target: 5432
        protocol: tcp
    networks:
      - isolated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3
    volumes:
      - psql-data:/var/lib/postgresql
      - ./migration.sql://docker-entrypoint-initdb.d/migration.sql:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  database-manager:
    container_name: ${APP_NAME}-database-manager
    image: dpage/pgadmin4:9.15.0
    ports:
      - host_ip: 127.0.0.1
        published: 4444
        target: 80
        protocol: tcp
    networks:
      - isolated
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:80/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3
    volumes:
      - db-manager_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      database:
        condition: service_healthy

  webserver:
    container_name: ${APP_NAME}-webserver
    restart: always
    image: nginx:stable-trixie-perl
    ports:
      - host_ip: 127.0.0.1
        published: 8080
        target: 4000
        protocol: tcp
      - host_ip: 127.0.0.1
        published: 3000
        target: 3000
        protocol: tcp
    networks:
      - isolated
      - shared
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/:/etc/certs/:ro
    healthcheck:
      test: ["CMD", "curl", "-fkS", "https://127.0.0.1:443"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      web:
        condition: service_healthy

  server:
    container_name: ${APP_NAME}-server
    restart: always
    image: ${APP_NAME}/spring:1.0
    build:
      context: ./
      dockerfile: Dockerfile
      target: spring
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - isolated
    depends_on:
      database:
        condition: service_healthy

  web:
    container_name: ${APP_NAME}-web
    restart: always
    image: ${APP_NAME}/angular:1.4
    build:
      context: ./
      dockerfile: Dockerfile
      target: angular
    networks:
      - isolated
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://127.0.0.1:4000').then(r=>console.log(r.status))",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy

networks:
  isolated:
    # internal: true
    driver: bridge
  shared:
    driver: bridge

volumes:
  psql-data:
  db-manager_data:
