events {}

http {
  upstream frontend { 
    least_conn;
    server web:4000;
   }

   upstream backend {
    least_conn;
    server server:3000;
   }

   server {
    listen 443 ssl;
    keepalive_timeout 70;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      proxy_pass http://frontend;
    }

    location /api/ {
      proxy_pass http://backend;
    }
   }
}